<?php
$element = $this->getElement();
$htmlId = $element->getHtmlId();

if ($element->getExpanded() !== null) {
    $collapseState = 1;
} else {
    $extra = Mage::getSingleton('admin/session')->getUser()->getExtra();
    if (isset($extra['configState'][$element->getId()])) {
        $collapseState = (int)$extra['configState'][$element->getId()];
    } else {
        $collapseState = 0;
    }
}
?>
<div class="section-config">
<div class="entry-edit-head collapseable">
    <a onclick="Fieldset.toggleCollapse('<?php echo $htmlId ?>', '<?php echo $this->getUrl('*/*/state/')?>'); return false;" href="#" id="<?php echo $htmlId ?>-head" class="">
        <?php echo $element->getLegend() ?>
    </a>
</div>
<input type="hidden" value="<?php echo $collapseState ?>" name="config_state[<?php echo $htmlId ?>]" id="<?php echo $htmlId ?>-state">
<fieldset id="<?php echo $htmlId ?>" class="config collapseable grid">
    <p>
        <?php echo $this->__('Use custom address formatting:').' '; ?>
        <?php $use_custom_address_formatting = Mage::getStoreConfig('moogento_core/config/use_custom_address_formatting'); ?>
        <select class="chosen" name="moogento_core[config][use_custom_address_formatting]">
            <option value="1" <?php echo ($use_custom_address_formatting) ? 'selected="selected"' : ""; ?>><?php echo $this->__('Yes').' '; ?></option>
            <option value="0" <?php echo ($use_custom_address_formatting) ? "" : 'selected="selected"'; ?>><?php echo $this->__('No').' '; ?></option>
        </select>
    </p>
    <table class="data" cellspacing="0">
        <thead>
        <tr class="headings">
            <th style="width: 75px">&nbsp;</th>
            <th style="width: 200px"><?php echo $this->__('Country') ?></th>
            <th><?php echo $this->__('Template') ?></th>
        </tr>
        </thead>
        <tbody class="toggle-light" data-bind="sortable: {data: list, afterMove: updateSort, options: sortableOptions}">
        <tr>
            <td>
                <span class="icon-drag"></span>
                <span style="display: inline-block">
                    <input type="hidden" data-bind="value: id, attr: {name: buildName('id')}" />
                    <input type="hidden" value="0" data-bind="attr: {name: buildName('enable')}" />
                    <input type="checkbox" value="1" data-bind="attr: {name: buildName('enable')}, checked: enable, switch: enable" />
                    <input type="hidden" data-bind="value: sort_number, attr: {name: buildName('sort_number')}" />
                </span>
                <span data-bind="click: $parent.removeCountryTemplate" class="fa fa-times" style="color: red; cursor: pointer"></span>
            </td>
            <td>
                <select class="chosen" data-bind="attr: {name: buildName('country_code')}, value: country_code, chosen: {width: '190px'}">
                    <?php 
                        $countryList = Mage::getResourceModel('directory/country_collection')->loadData()->toOptionArray(false);
                        foreach($countryList as $country){
                            echo '<option value="'.$country['value'].'">'.$country['label'].'</option>';
                        } 
                    ?>
                </select>
            </td>
            <td>
                <textarea rows="3" cols="30" data-bind="value: country_template, attr: {name: buildName('country_template')}" ></textarea>
            </td>
        </tr>
        </tbody>
    </table>
    <h5>
        <button class="add" data-bind="click: addCountryTemplate"><span><span><?php echo $this->__('Add') ?></span></span></button>
    </h5>
    <button class="add" onclick="setLocation('<?php echo $this->getUrl('*/system_config_country_template/addDefaults') ?>');return false;"><span><span><?php echo $this->__('Add Defaults') ?></span></span></button>
</fieldset>
<script type="text/javascript">
    Fieldset.applyCollapse('<?php echo $htmlId ?>');
    ko.applyBindings(new CountryTemplateConfigModule.CountryTemplates(<?php echo $this->_getJson() ?>), document.getElementById('<?php echo $htmlId ?>'));
    URL_for_destoy_country_templates = '<?php echo Mage::helper("adminhtml")->getUrl("*/system_config_country_template/destroyCountryTemplate"); ?>';
</script>
<style>
    .icon-drag {
        cursor: move;
    }
</style>
</div>