<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2015 Amasty (https://www.amasty.com)
 * @package Amasty_Xnotif
 */   
?>
<?php $_productId = Mage::registry('product')->getId()?>
<div class="amxnotif-block" style=" margin-bottom: 5px;">
	<label style="color: #2F2F2F;font-weight: bold; float:none;" ><?php echo $this->__("Get Instant Notification When I'm Back In Stock!"); ?> </label><br/>
        <input type="text" name="guest_email" id="amxnotif_guest_email-<?php echo $_productId;?>" onKeyPress="return checkIt(event, '<?php echo $this->escapeHtml(Mage::helper('amxnotif')->getEmailUrl('stock'));?>', $('button-email-send-<?php echo $_productId;?>'))" class="input-text amcart-email-notify" size="30"  placeholder="Enter Your Email Address."/>
	<input type="hidden" name="product_id" value="<?php echo $_productId;?>" />
	<input type="hidden" name="type" value="email"/>
	<input type="hidden" name="parent_id" value="<?php echo Mage::registry('par_product_id')?>" />
	<input type="hidden" name="<?php echo Mage_Core_Controller_Front_Action::PARAM_NAME_URL_ENCODED ?>" value="<?php echo Mage::helper('amxnotif')->getUrl()?>" />
	<button type="button" id="button-email-send-<?php echo $_productId;?>" class="button btn-cart amcart-ignore" onclick="send_alert_email('<?php echo $this->escapeHtml(Mage::helper('amxnotif')->getEmailUrl('stock'));?>', this)" title="<?php echo $this->__('Subscribe'); ?>"><span><span><?php echo $this->__('NOTIFY ME!'); ?></span></span> </button>
</div>   
 
