<?php
    $_productCollection = $this->getLoadedProductCollection();
    $_helper            = $this->helper('catalog/output');
?>
<?php if(!$_productCollection->getSize()): ?>

<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
    <ul id="topsellerjqurosal" class="jcarousel-skin-tango">
    <?php $i=0; foreach ($_productCollection as $_product): ?>
       <li>
                        <div class="ps_part">
                                <ul>
                                    <li>
                                        
                                            <div class="ps_img_cntr">
                                                <div class="ps_img">
                                       <a data-link="topseller" id="pb_item_<?php echo $_product->getId() ?>" class="EnableQuickView" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>" >
                                            <img height="115" width="115"  src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(115, 115) ?>" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" />
                                        </a>
                                                </div>
                                            </div>
                                            <div class="quickview">&nbsp;</div>
                                        </a>
                                    </li>
                                    <li class="font14_blk"><a class="font14_blk" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>)">
                                            <?php
                                              $Lengthname = $this->htmlEscape($_product->getName());
                                             if(strlen($Lengthname) > 16)
                                    echo substr($Lengthname,0,16).'...'; 
                                    else 
                                    echo substr($Lengthname,0,16);
                                             
                                             
                                             ?>
                                        </a>
                                    </li>
<li class="font12_gry"><?php $length = $this->htmlEscape(strip_tags($_product->getShortDescription()));
                                   if(strlen($length) > 18)
                                    echo substr($length,0,18).'...'; 
                                    else 
                                    echo substr($length,0,18); ?></li>
                                    <li class="mrgn_t5"><span class="font16_red"><?php echo $this->getPriceHtml($_product, true, '-new') ?></span>
                                    </li>
<!--                                    <li class="font14b_blk">SAVE $888.00</li>-->
<!--                                    <li class="mrgn_t5"><a class="link12_red" href="#">+ Add to compare</a></li>-->
                                    <?php $_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product) ?>

                                    <li class="mrgn_t5"><a class="link12_red" href="<?php echo $_compareUrl ?>">+ Add to compare</a></li> 
                                    <?php if ($_product->isSaleable()): ?>

                                            <li class="mrgn_t5">
                                           <!-- <a class="buy_btn" href="<?php echo $_product->getProductUrl(); ?>">BUY NOW</a>-->
                                            </li>

                                            
                                            
                                        <?php else: ?>
                                           <li class="mrgn_t5"><?php echo $this->__('Out of stock') ?></li>
                                        <?php endif; ?>
                                    
                                </ul>
                            </div>
                        
                    <?php //echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                </li>
        <?php endforeach ?>
        </ul>        
        <div  id="topseller" class="slidmain" style="float: left;display:none;"></div>
    <?php endif; ?>