<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2015 Amasty (https://www.amasty.com)
 * @package Amasty_Promo
 */
?>
<?php
$products = $this->getNewItems();
?>
<?php if (sizeof($products) > 0): ?>
    <script type="text/javascript">
  
    </script>

    <div id="ampromo-overlay" style="display: none;">
        <div id="ampromo-items" class="<?php echo sizeof($products) > 2 ? 'amcarousel' : ''?>">
<!--            <h4>--><?php //echo $this->__('Free Items')?><!--</h4>-->
            <div class="popup_middle gift_middle">
                <div class="popup_mid_wrap">
                    <div class="comman mrgn_t20">
                        <div class="popup_left">
                            <div id="gift-wellcome" style="display:none" class="popup_left_txt1">CONGRATULATIONS!<br />YOU'RE ELIGIBLE
                                <br />FOR A <span class="popup_left_txt2">FREE GIFT</span>
                                <div class="popup_left_txt3">
                                    <?php echo  Mage::getStoreConfig('ampromo/gift/spend');?>
                                    <br><br>
                                    <a href="javascript:;" onclick="$('ampromo-overlay').fade();" class="chk_offer_close link14_gry2">NO THANKS</a>
                                </div>
                            </div>
                            <div id="bonus-wellcome" class="popup_left_txt1">CONGRATULATIONS!<br />YOU'RE ELIGIBLE
                                <br />FOR A <span class="popup_left_txt2">Bonus</span>
                                <div class="popup_left_txt3">
                                    <br><br>
                                    <a href="javascript:;" onclick="ampromo_close_firstload();" class="chk_offer_close link14_gry2">NO THANKS</a>
                                </div>
                            </div>
                        </div>
                        <div class="popup_right">
                            <img src="<?php echo $this->getSkinUrl("images/popup_img.png") ?>" />
                        </div>
                    </div>
                </div>
            </div>
            <a href="javascript:" class="close"></a>

            <?php echo $this->getLayout()->createBlock('core/template')->setTemplate('catalog/product/view/options/js.phtml')->toHtml() ?>
            <?php echo $this->getLayout()->createBlock('core/html_calendar')->setTemplate('page/js/calendar.phtml')->toHtml() ?>

<!--            <a href="javascript:" class="ampromo-carousel-control prev" rel="prev">Previous slide</a>-->
            <div id="ampromo-wrapper">
                <div id="ampromo-content">
                    <?php foreach ($products as $product): ?>
                            <?php if(Mage::helper('ampromo/bonus')->IsFreeShippingGiftInCart() && $product->getSKU() == Mage::helper('ampromo/bonus')->_GiftSku) continue; ?>
                            <div class="ampromo-item" data-product-id="<?php echo $product->getId()?>" data-product-sku="<?php echo $product->getSku()?>"<?php if($product->getTypeId() == 'amgiftcard'):?>style="width: 400px;"<?php endif;?>>
                                <form method="POST" action="<?php echo $this->getFormActionUrl()?>" class="ampromo_items_form" id="ampromo_items_form-<?php echo $product->getId()?>">
                                    <input type='hidden' name='referer' value='<?php echo $this->_getReferer()?>' />

                                    <img src="<?php echo $product->getSmallImageUrl(176, 200) ?>" class="ampromo-item-image"/>
                                    <div class="gift-price-box">
                                        <div class="free-price">Free</div>
                                        <?php  $product_block = new Mage_Catalog_Block_Product;
                                        echo $product_block->getPriceHtml($product);
                                        unset($product_block);
                                        ?>
                                    </div>
                                    <div class="ampromo-item-title">
                                        <?php if ($product->getVisibility() != Mage_Catalog_Model_Product_Visibility::VISIBILITY_NOT_VISIBLE):?>
                                            <h4><a href="<?php echo $product->getProductUrl()?>"><?php echo $product->getName()?></a></h4>
                                        <?php else: ?>
                                            <h4><?php echo $product->getName()?></h4>
                                        <?php endif?>
                                    </div>
                                    <div class="ampromo-item-options"  <?php if($product->getTypeId() == 'amgiftcard'):?>style="overflow-y: scroll; max-height: 300px"<?php endif;?>>
										<?php
                                        $_blockOpt='';
										switch($product->getTypeId()){
											case 'configurable';
												$_blockOpt = 'catalog/product_view_type_configurable';
												$_templateOpt = 'amasty/ampromo/items/configurable.phtml';
												break;
											case 'bundle':
												$_blockOpt = 'ampromo/items_bundle';
												$_templateOpt = 'bundle/catalog/product/view/type/bundle/options.phtml';
												break;
											case 'amgiftcard':
												$_blockOpt = 'amgiftcard/catalog_product_view_type_giftCard';
												$_templateOpt = 'amasty/amgiftcard/catalog/product/view/type/giftcard.phtml';
												break;
										}
										if(!empty($_blockOpt) && !empty($_templateOpt)) {
											echo $this->getLayout()
                                                ->createBlock(
                                                    $_blockOpt,
                                                    'ampromo_item_' . $product->getId(),
                                                    array('product' => $product)
                                                )
												->setProduct($product)
												->setTemplate($_templateOpt)
												->toHtml()
											;
										}
										?>

                                        <?php echo $this->getLayout()
                                            ->createBlock('ampromo/items_options', '', array('product' => $product))
                                            ->toHtml()
                                        ;?>
                                    </div>

                                    <input type="hidden" value="<?php echo $product->getId() ?>" name="product_id" />

                                    <div class="ampromo-item-buttons">
                                        <button type="button" title="<?php echo $this->__('Add to cart')?>" class="button btn-cart add"><span><span><?php echo $this->__('Add to cart')?></span></span></button>
                                    </div>
                                </form>
                            </div>

                    <?php endforeach ?>
                </div>
            </div>
<!--            <a href="javascript:" class="ampromo-carousel-control next" rel="next">Next slide</a>-->
        </div>
    </div>
<?php endif ?>
