<?php
$loc = $this->getLocations()->getFirstItem();
?>
<div class="page-title">
    <h1><?php echo $loc->getTitle(); ?></h1>
</div>
<section class="loc-page" itemscope itemtype="http://data-vocabulary.org/Place">
    <div class="loc-page-map-wrap"><?php echo $this->getChildHtml('map') ?></div>
    <div class="loc-page-data"><?php echo $this->getChildHtml('info') ?></div>
  <div class="loc-page-store-manager">
      <?php echo $this->getLayout()->createBlock('ak_locator/search')->setTemplate('locator/location/store_manager.phtml')->toHtml(); ?>
  </div>
  <div class="loc-page-additional"><?php echo $this->getChildHtml('attributes') ?></div>
</section>

<!--<section class="loc-nearby">
  <?php /*echo $this->getChildHtml('others') */?>
</section>-->
