<?php 
/** 
* Moogento
* 
* SOFTWARE LICENSE
* 
* This source file is covered by the Moogento End User License Agreement
* that is bundled with this extension in the file License.html
* It is also available online here:
* http://www.moogento.com/License.html
* 
* NOTICE
* 
* If you customize this file please remember that it will be overwrtitten
* with any future upgrade installs. 
* If you'd like to add a feature which is not in this software, get in touch
* at www.moogento.com for a quote.
* 
* ID          pe+sMEDTrtCzNq3pehW9DJ0lnYtgqva4i4Z=
* File        backorders.phtml
* @category   Moogento
* @package    pickPack
* @copyright  Copyright (c) 2014 Moogento <info@moogento.com> / All rights reserved.
* @license    http://www.moogento.com/License.html
*/ 
?>
<?php 
$results_array = Mage::helper('moogento_shipeasy/functions')->getValueSetStockOption("backorder_images_of_status");
if (isset($results_array[$this->getOrder()->getBackorder()])){
    $result = $results_array[$this->getOrder()->getBackorder()];
    if($this->_ifOrderTransparent()){
        echo '';
    } else {
        if(isset($result['img'])){
            echo ('<img src="'.$result['img'].'" title="'.$result['label'].'" width="16" height="16" />');
        } else {
            echo $result['label'];
        }
    }
} else {
    echo '';
}
?>
