<?php 
/** 
* Moogento
* 
* SOFTWARE LICENSE
* 
* This source file is covered by the Moogento End User License Agreement
* that is bundled with this extension in the file License.html
* It is also available online here:
* http://www.moogento.com/License.html
* 
* NOTICE
* 
* If you customize this file please remember that it will be overwrtitten
* with any future upgrade installs. 
* If you'd like to add a feature which is not in this software, get in touch
* at www.moogento.com for a quote.
* 
* ID          pe+sMEDTrtCzNq3pehW9DJ0lnYtgqva4i4Z=
* File        backorders.phtml
* @category   Moogento
* @package    pickPack
* @copyright  Copyright (c) 2014 Moogento <info@moogento.com> / All rights reserved.
* @license    http://www.moogento.com/License.html
*/ 
?>
<?php $_order = $this->getOrder(); ?>
<div class="inputs_for_admin_email">
    <input type="text" class="text_for_admin_email"
        value="<?php echo $_order->getEmailFromAdmin() ?>" 
        data-value="<?php echo $_order->getEmailFromAdmin() ?>" 
        data-changeurl="<?php echo $this->getUrl('*/sales_order_process/orderEmailEditFromGrid') ?>" 
        data-orderid="<?php echo $_order->getId() ?>" 
    />
    <button title="Submit" type="button" class="submit_for_admin_email"><span>Submit</span></button>
    <button title="Cancel" type="button" class="cancel_for_admin_email"><span>Cancel</span></button>
</div>
<div>
<?php echo $this->getEmailsList();?>
</div>
<span class="edit-icon"></span>
