<div class="timer_banner">
    <?php
        $bannerYes = Mage::getStoreConfig('samedd/sameddgroup/samedaydisplay');
        $delivTime = Mage::getStoreConfig('samedd/sameddgroup/delivery_time');
        $banner    = Mage::getStoreConfig('samedd/sameddgroup/samedaybanner');
        $delivTime = implode(':', explode(',', $delivTime));
    ?>
    <?php if ($bannerYes == 1): ?> 
        <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'catalog/product/watermark/' . $banner ?>"/>
    <?php else: ?>
        <div class="timerCoundown">
            <div class="countdown-container" id="timerCoundown"></div>
        </div>
        <div class="timerClosed">
            <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'catalog/product/watermark/' . $banner ?>"/>
        </div>

        <script type="text/template" id="timerCoundown-template">
            <div class="time <%= label %>">
                <span class="count curr top"><%= curr %></span>
                <span class="count next top"><%= next %></span>
                <span class="count next bottom"><%= next %></span>
                <span class="count curr bottom"><%= curr %></span>
                <span class="label"><%= label.length < 6 ? label : label.substr(0, 3)  %></span>
            </div>
        </script>
        <script>
            jQblvg(document).ready(function($) {
                jQblvg('.timerClosed').hide();
                //var myVar = setInterval(function() {
                    mytimer()
                //}, 1000);

                //function mytimer() {
                    var nowtime   = "<?php echo date('d F Y H:i:s', Mage::getModel('core/date')->timestamp(time())) ?>";
                    var timestamp = Date.parse(nowtime);

                    var dateBegin = new Date();
                    dateBegin.setTime(timestamp);
                    var dateEnd   = stringToDate("<?php echo date('Y-m-d') . ' ' . $delivTime ?>");

                    if (dateBegin < dateEnd) {

                        //var labels     = ['hours', 'minutes', 'seconds'];
                        var labels     = ['hours1', 'hours2', 'minutes1', 'minutes2', 'seconds1', 'seconds2'];
                        var template   = _.template($('#timerCoundown-template').html());
                        //var parser     = /([0-9]{2})/gi;
                        var parser     = /([0-9]{1})/gi;
                        var $delivery  = $('#timerCoundown');

                        // Parse countdown string to an object
                        function strfobj(str) {
                            var parsed = str.match(parser),
                            obj = {};
                            labels.forEach(function(label, i) {
                                obj[label] = parsed[i]
                            });

                            return obj;
                        }

                        // Return the time components that diffs
                        function diff(obj1, obj2) {
                            var diff = [];
                            labels.forEach(function(key) {
                                if (obj1[key] !== obj2[key]) {
                                    diff.push(key);
                                }
                            });

                            return diff;
                        }

                        var currDate   = '00:00:00';
                        var nextDate   = '00:00:00';

                        // Build the layout
                        var initData = strfobj(currDate);
                        labels.forEach(function(label, i) {
                            $delivery.append(template({
                                curr : initData[label],
                                next : initData[label],
                                label: label
                            }));
                        });
                        // Starts the countdown
                        $delivery.countdown(dateBegin, dateEnd, function(event) {
                            //var newDate = event.strftime('%w:%d:%H:%M:%S');
                            var newDate = event.strftime('%H:%M:%S');
                            if (newDate !== nextDate) {
                                currDate = nextDate;
                                nextDate = newDate;
                                // Setup the data
                                var data = {
                                    'curr': strfobj(currDate),
                                    'next': strfobj(nextDate)
                                };
                                // Apply the new values to each node that changed
                                diff(data.curr, data.next).forEach(function(label) {
                                    var selector = '.%s'.replace(/%s/, label),
                                    $node = $delivery.find(selector);
                                    // Update the node
                                    $node.removeClass('flip');
                                    $node.find('.curr').text(data.curr[label]);
                                    $node.find('.next').text(data.next[label]);
                                    // Wait for a repaint to then flip
                                    _.delay(function($node) {
                                        $node.addClass('flip');
                                    }, 5, $node);
                                });
                            }
                        });

                        //clearInterval(myVar);
                    } else {
                        $('.timerCoundown').hide();
                        $('.timerClosed').show();
                    }    
                //}
            });
        </script>
    <?php endif ?>
</div>
