<?php
/**
 * One Step Checkout Manager : One Step Checkout Manager (OPCB Unit)
 *
 * @category:    Aitoc
 * @package:     Aitoc_Aitcheckout / Aitoc_Aitcheckout
 * @version      1.0.9 - 1.4.9
 * @license:     Nichj4LUEMsSNLvlLmobwL49OlCNVmKqxOe78SZxGK
 * @copyright:   Copyright (c) 2014 AITOC, Inc. (http://www.aitoc.com)
 */
?>
<?php
$giftcard =Mage::getSingleton('checkout/session')->getQuote()->getCouponCode2();
?>
<div id="co-giftcard-form">
    <fieldset>
        <div style="display:none;" id="giftcard-notice" class="error-msg"></div>

        <ul class="form-list">
            <li class="left">
                <label for="giftcard_code"><?php echo $this->__('Giftcard code:') ?></label>
                <input type="hidden" id="remove_giftcard" name="remove_giftcard" value="0" />
                <div class="input-box">
                    <input class="input-text <?php echo (strlen($giftcard)) ? 'required-entry' : '' ?>" id="giftcard_code" name="giftcard_code" value="<?php echo $this->htmlEscape($giftcard) ?>" />
                </div>
            </li>
            <li class="right">
                <button id="giftcard-apply-button" type="button" title="<?php echo Mage::helper('checkout')->__('Apply Giftcard') ?>" class="button btn-black" onclick="giftcardSubmit(false);" value="<?php echo Mage::helper('checkout')->__('Apply Giftcard') ?>"><span><span><?php echo Mage::helper('checkout')->__('Apply Giftcard') ?></span></span></button>
                <?php if(strlen($giftcard)): ?>
                    <button id="giftcard-cancel-button" type="button" title="<?php echo Mage::helper('checkout')->__('Cancel Giftcard') ?>" class="button btn-black" onclick="giftcardSubmit(true);" value="<?php echo Mage::helper('checkout')->__('Cancel Giftcard') ?>"><span><span><?php echo Mage::helper('checkout')->__('Cancel Giftcard') ?></span></span></button>
                <?php endif;?>
            </li>
        </ul>
    </fieldset>
</div>
<div id="giftcard-waiting" class="aitcheckout-wait" style="display:none"><img src="<?php echo Mage::getDesign()->getSkinUrl('images/opc-ajax-loader.gif'); ?>" /></div>
<script type="text/javascript">
    //<![CDATA[
    giftcardSubmit = function (isRemove) {
        if (isRemove) {
            $('remove_giftcard').value = "1";
        } else {
            $('remove_giftcard').value = "0";
        }
    }
    //]]>
</script>
<script type="text/javascript">
    //<![CDATA[
    aitCheckout.createStep('giftcard',{
            giftcardUpdateUrl : '<?php echo $this->getUrl('aitcheckout/cart/giftcardPost', array('_secure'=>true)) ?>'
        }, {
            doCheckErrors : false,
            isLoadWaiting : true,
            isUpdateOnReload : false,
            reloadMessage: <?php echo $this->helper('aitcheckout')->isShowCheckoutInCart() && $this->helper('aitcheckout')->isCompactDesign()?'false':'true' ?>,
            container: 'checkout-step-giftcard'
        }
    );
    aitCheckout.getStep('giftcard').initGiftcard('giftcard-apply-button', 'giftcard-cancel-button');
    //]]>
</script>