<script type="text/javascript">
    //<![CDATA[
    function saveCondition() {
        new Ajax.Request('<?php echo $this->getAjaxCheckUrl() ?>', {
            method:     'get',
            onSuccess: function(transport){
                if (transport.responseText){
                    alert('Saved')
                }
            }
        });
    }
    //]]>
</script>

<?php echo $this->getButtonHtml() ?>