<?php
/**
* Braintree Payments Extension
*
* This source file is subject to the Braintree Payment System Agreement (https://www.braintreepayments.com/legal)
*
* DISCLAIMER
* This file will not be supported if it is modified.
*
* @copyright   Copyright (c) 2015 Braintree. (https://www.braintreepayments.com/)
*/
?>
<?php $_code        = Braintree_Payments_Model_Creditcard::PAYMENT_METHOD_CODE ?>
<?php $defaultData  = $this->getDefaultCartData(); ?>

<div class="page-title">
    <h1><?php echo $this->getTitle() ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="tool-tip" id="payment-tool-tip" style="display:none;">
    <div class="btn-close"><a href="#" id="payment-tool-tip-close" title="<?php echo $this->__('Close') ?>"><?php echo $this->__('Close') ?></a></div>
    <div class="tool-tip-content"><img src="<?php echo $this->getSkinUrl('images/cvv.gif') ?>" alt="<?php echo $this->__('Card Verification Number Visual Reference') ?>" title="<?php echo $this->__('Card Verification Number Visual Reference') ?>" /></div>
</div>
<form action='<?php echo $this->getFormAction() ?>' method="post" id="form-validate">
    <input type="hidden" name="nonce" id="<?php echo Mage::helper('braintree_payments')->getNonceInputId() ?>" value="" />
    <div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Credit Card') ?></h2>
        <ul class="form-list">
            <li>
                <label for="credit_card_cardholder_name" class="required"><em>*</em><?php echo $this->__('Cardholder Name') ?></label>
                <div class="input-box">
                    <input type="text" class="input-text required-entry " id="<?php echo $_code ?>_cardholder_name" value="<?php echo $this->getPostParam('creditCard.cardholderName', $defaultData->getCartholder()) ?>" data-braintree-name="cardholder_name">
                </div>
            </li>
            <li>
                <label for="<?php echo $_code ?>_cc_number" class="required "><em>*</em><?php echo $this->__('Credit Card Number') ?></label>
                <div class="input-box">
                    <input type="text" class="input-text required-entry validate-cc-number" id="<?php echo $_code ?>_cc_number" data-braintree-name="number" autocomplete="off">
                </div>
                <input type="hidden" id="credit_card_type" value=''/>
            </li>
            <li class="sp-methods">
                <label for="<?php echo $_code ?>_expiration" class="required"><em>*</em><?php echo $this->__('Expiration Date') ?></label>
                <div class="input-box">
                    <div class="v-fix">
                        <select id="<?php echo $_code ?>_expiration" class="month validate-cc-exp required-entry" data-braintree-name="expiration_month">
                            <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                                <option value="<?php echo $k ? $k : '' ?>"<?php if ($k == $defaultData->getExpMonth()) : ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                            <?php endforeach ?>
                        </select>
                    </div>
                    <div class="v-fix">
                        <select id="<?php echo $_code ?>_expiration_yr" class="year required-entry" data-braintree-name="expiration_year">
                            <?php foreach ($this->getCcYears() as $k=>$v): ?>
                                <option value="<?php echo $k ? $k : ''; ?>"<?php if ($k == $defaultData->getExpYear()): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                            <?php endforeach ?>
                        </select>
                    </div>
                </div>
            </li>
            <?php if ($this->hasVerification()): ?>
                <li class="sp-methods">
                    <label for="<?php echo $_code ?>_cc_cid" class="required"><em>*</em><?php echo $this->__('CVV') ?></label>
                    <div class="input-box">
                        <input type="text" class="input-text cvv required-entry validate-cc-cvn validate-cc-cvn-autodetect" id="<?php echo $_code ?>_cc_cid" value="" data-braintree-name="cvv" autocomplete="off">
                        <a href="#" class="cvv-what-is-this"><?php echo $this->__('What is this?') ?></a>
                    </div>
                </li>
            <?php endif; ?>
            <?php if ($this->canShowMakeDefault()): ?>
                <li>
                    <label for="credit_card_options_make_default"><?php echo $this->__('Make Default') ?></label>
                    <div class="input-box">
                        <input type="checkbox" name="credit_card[options][make_default]" id="credit_card_options_make_default" value="1" <?php echo $defaultData->getIsCCDefault() ? "checked" : "" ?>>
                    </div>
                </li>
            <?php endif; ?>
        </ul>
    </div>
    <div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Billing Address') ?></h2>
        <ul class="form-list">
            <li>
                <label for="billing_address_first_name" class="required"><em>*</em><?php echo $this->__('First Name') ?></label>
                <div class="input-box">
                    <input type="text" class="input-text required-entry " name="credit_card[billing_address][first_name]" id="billing_address_first_name" value="<?php echo $this->getPostParam('customer.creditCard.billingAddress.firstName', $defaultData->getFirstName()) ?>">
                </div>
            </li>
            <li>
                <label for="billing_address_last_name" class="required"><em>*</em><?php echo $this->__('Last Name') ?></label>
                <div class="input-box">
                    <input type="text" class="input-text required-entry " name="credit_card[billing_address][last_name]" id="billing_address_last_name" value="<?php echo $this->getPostParam('customer.creditCard.billingAddress.lastName', $defaultData->getLastName()) ?>">
                </div>
            </li>
            <li>
                <label for="billing_address_company"><?php echo $this->__('Company') ?></label>
                <div class="input-box">
                    <input type="text" class="input-text " name="credit_card[billing_address][company]" id="billing_address_company" value="<?php echo $this->getPostParam('customer.creditCard.billingAddress.company', $defaultData->getCompany()) ?>">
                </div>
            </li>
            <li>
                <label for="billing_address_street_address" class="required"><em>*</em><?php echo $this->__('Street Address') ?></label>
                <div class="input-box">
                    <input type="text" class="input-text required-entry " name="credit_card[billing_address][street_address]" id="billing_address_street_address" value="<?php echo $this->getPostParam('customer.creditCard.billingAddress.streetAddress', $defaultData->getStreetAddress()) ?>">
                </div>
            </li>
            <li>
                <label for="billing_address_extended_address"><?php echo $this->__('Extended Address') ?></label>
                <div class="input-box">
                    <input type="text" class="input-text " name="credit_card[billing_address][extended_address]" id="billing_address_extended_address" value="<?php echo $this->getPostParam('customer.creditCard.billingAddress.extendedAddress', $defaultData->getExtendedAddress()) ?>">
                </div>
            </li>
            <li>
                <label for="billing_address_locality" class="required"><em>*</em><?php echo $this->__('City') ?></label>
                <div class="input-box">
                    <input type="text" class="input-text required-entry " name="credit_card[billing_address][locality]" id="billing_address_locality" value="<?php echo $this->getPostParam('customer.creditCard.billingAddress.locality', $defaultData->getLocality()) ?>">
                </div>
            </li>
            <li>
                <label for="billing_address_region" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
                <div class="input-box">
                        <select id="billing_address_region_id" name="credit_card[billing_address][region_id]" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;">
                            <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                        </select>
                        <script type="text/javascript">
                        //<![CDATA[
                            $('billing_address_region_id').setAttribute('defaultValue',  "<?php echo $this->getPostParam('customer.creditCard.billingAddress.region', $defaultData->getRegionId()) ?>");
                        //]]>
                        </script>
                    <input type="text" class="input-text " name="credit_card[billing_address][region]" id="billing_address_region" value="<?php echo $this->getPostParam('customer.creditCard.billingAddress.region', $defaultData->getRegion()) ?>">
                </div>
            </li>
            <li>
                <label for="billing_address_postal_code" class="required"><em>*</em><?php echo $this->__('Postal Code') ?></label>
                <div class="input-box">
                    <input type="text" class="input-text required-entry validate-zip-international " name="credit_card[billing_address][postal_code]" id="billing_address_postal_code" value="<?php echo $this->getPostParam('customer.creditCard.billingAddress.postalCode', $defaultData->getPostalCode()) ?>">
                </div>
            </li>
            <li>
                <label for="billing_address_country" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
                <div class="input-box">
                    <?php $default = $this->getPostParam('customer.creditCard.billingAddress.countryCodeAlpha2', $defaultData->getCountryCodeAlpha2()) ?>
                    <?php echo $this->countrySelect('credit_card' . '[billing_address][country_code_alpha2]', 'billing_address_country', $default) ?>
                </div>
            </li>
        </ul>
    </div>
    <div class="buttons-set">
        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
        <button type="button" id="submit-button" class="button" title="<?php echo $this->__('Submit') ?>" onclick="dataForm.submitForm(this)"><span><span><?php echo $this->__('Submit') ?></span></span></button>
        <span class="please-wait" id="please-wait" style="display:none;">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Please Wait...') ?>" title="<?php echo $this->__('Please Wait...') ?>" class="v-middle" /> <?php echo $this->__('Please Wait...') ?>
        </span>
        <p class="back-link"><a href="<?php echo $this->getBackUrl() ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[

    var dataForm = new VarienForm('form-validate', true);
    dataForm.submitForm = function(button) {
        if (this.validator.validate()) {
            if ($('billing_address_region').style['display'] == 'none') {
                $('billing_address_region').value = $('billing_address_region_id').value;
            }
            $('billing_address_region_id').disabled = true;
            $('submit-button').disabled = true;
            $('please-wait').show();

            var submitForm = function() {
                $('form-validate').submit();
                $('billing_address_region_id').disabled = false;
                $('submit-button').disabled = false;
            }
            braintreeUtils.getPaymentNonce(
                '<?php echo $_code ?>',
                false,
                submitForm
            );
        }
    }.bind(dataForm);



    new RegionUpdater('billing_address_country', 'billing_address_region', 'billing_address_region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'billing_address_postal_code');

    var ccTypesObject = $H({
        'VI': [new RegExp('^4[0-9]{12}([0-9]{3})?$'), new RegExp('^[0-9]{3}$')],
        'MC': [new RegExp('^5[1-5][0-9]{14}$'), new RegExp('^[0-9]{3}$')],
        'AE': [new RegExp('^3[47][0-9]{13}$'), new RegExp('^[0-9]{4}$')],
        'DI': [new RegExp('^6011[0-9]{12}$'), new RegExp('^[0-9]{3}$')],
        'JCB': [new RegExp('^(3[0-9]{15}|(2131|1800)[0-9]{11})$'), new RegExp('^[0-9]{3,4}$')],
        'OT': [false, new RegExp('^([0-9]{3}|[0-9]{4})?$')]
    });
    var ccTypes = ccTypesObject._object;

    Validation.addAllThese([
        ['validate-cc-cvn-autodetect', 'Please enter a valid credit card verification number.', function(v) {
            var ccType = $('credit_card_type').value;
            if(ccTypes.hasOwnProperty(ccType)) {
                var ccRegex = ccTypes[ccType][1];
                if (!ccRegex.test(v)) {
                    return false;
                }
            }
            return true;
        }]]);

    Event.observe($('<?php echo $_code ?>_cc_number'),'blur',function(){
            var ccNumber = this.value;
            ccNumber = ccNumber.replace(/\D/g,''); //remove all but the digits
            var matchFound = false;
            for(var ccType in ccTypes) {
                if(ccTypes.hasOwnProperty(ccType)) {
                    var ccRegex = ccTypes[ccType][0];
                    if(ccRegex && ccNumber.match(ccRegex)) {
                        matchFound = true;
                        break;
                    }
                }
            }
            if (matchFound) {
                $('credit_card_type').value = ccType;
            } else {
                $('credit_card_type').value = 'OT';
            }
    });

    function toggleToolTip(event){
        if($('payment-tool-tip')){
            $('payment-tool-tip').setStyle({
                left: (Event.pointerX(event)-100)+'px',
                top: (Event.pointerY(event)-200)+'px'
            });
            $('payment-tool-tip').toggle();
        }
        Event.stop(event);
    }

    $$('.cvv-what-is-this').each(function(element){
        Event.observe(element, 'click', toggleToolTip);
    });
    if($('payment-tool-tip-close')){
        Event.observe($('payment-tool-tip-close'), 'click', toggleToolTip);
    }
//]]>
</script>
