<?php
$_productCollection = $this->getLoadedProductCollection();
$_helper = $this->helper('catalog/output');
?>
<?php if (!$_productCollection->getSize()): ?>

    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
    <ul id="topsellerjqurosal" class="jcarousel-skin-tango">
        <?php $i = 0;
        foreach ($_productCollection as $_product): ?>
            <li>
                <div class="ps_part">
                    <ul>
                        <li>

                            <div class="ps_img_cntr">
                                <div class="ps_img">
                                    <a data-link="topseller" id="pb_item_<?php echo $_product->getId() ?>"
                                       class="EnableQuickView" href="<?php echo $_product->getProductUrl() ?>"
                                       title="<?php echo $this->htmlEscape($_product->getName()) ?>">
                                        <img height="176" width="176"
                                             src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(176, 176) ?>"
                                             alt="<?php echo $this->htmlEscape($_product->getName()) ?>"/>
                                    </a>
                                </div>
                            </div>
                        </li>
                        <li class="mrgn_t5"><span
                                class="font16_red"><?php echo $this->getPriceHtml($_product, true, '-new') ?></span>
                        </li>
                        <li class="font14_blk product-name"><a href="<?php echo $_product->getProductUrl() ?>"
                                                  title="<?php echo $this->htmlEscape($_product->getName()) ?>">
                                <?php
                                echo $this->htmlEscape($_product->getName());
                                ?>
                            </a>
                        </li>
                        <li class="font12_gry std">
                            <?php echo $this->htmlEscape(strip_tags($_product->getShortDescription())); ?>
                        </li>
                        <?php 
                        $enable_button_cart = Mage::getStoreConfig("catalog/frontend/enable_button_cart");
                        ?>
                        <?php if ($enable_button_cart): ?>
                            <?php if ($_product->isSaleable()): ?>

                                <li class="mrgn_t5 actions">
                                    <a class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">Add to cart</a>
                                    <!--<a class="btn-cart" href="<?php /*echo $_product->getProductUrl(); */?>">Add to cart</a>-->
                                </li>
                            <?php else: ?>
                                <li class="mrgn_t5"><?php echo $this->__('Out of stock') ?></li>
                            <?php endif; ?>
                        <?php endif ?>

                    </ul>
                </div>

                <?php //echo $this->getReviewsSummaryHtml($_product, 'short') ?>
            </li>
        <?php endforeach ?>
    </ul>
    <div id="topseller" class="slidmain" style="float: left;display:none;"></div>
<?php endif; ?>