<ul class="level0-sub customer_service">
    <li class="level1 first parent">
        <h4><?php echo Mage::helper('local')->getStaticBlockTitle('customer_service') ?></h4>
        <?php echo Mage::helper('local')->getStaticBlockHtml('customer_service') ?>
    </li>
</ul>
</dd>
<dd>
<ul class="level0-sub customer_servic_connect">
    <li class="level1 first parent">
        <h4>
            &nbsp;
        </h4>
    </li>
    <li>
        <?php echo Mage::helper('local')->getStaticBlockHtml('connect_with_us_red') ?>
    </li>
</ul>
