<?php
$element = $this->getElement();
$htmlId = $element->getHtmlId();

if ($element->getExpanded() !== null) {
    $collapseState = 1;
} else {
    $extra = Mage::getSingleton('admin/session')->getUser()->getExtra();
    if (isset($extra['configState'][$element->getId()])) {
        $collapseState = (int)$extra['configState'][$element->getId()];
    } else {
        $collapseState = 0;
    }
}

?>
<div class="section-config" xmlns="http://www.w3.org/1999/html">
    <div class="entry-edit-head collapseable">
        <a onclick="Fieldset.toggleCollapse('<?php echo $htmlId ?>', '<?php echo $this->getUrl('*/*/state/')?>'); return false;" href="#" id="<?php echo $htmlId ?>-head" class="">
            <?php echo $element->getLegend() ?>
        </a>
    </div>
    <input type="hidden" value="<?php echo $collapseState ?>" name="config_state[<?php echo $htmlId ?>]" id="<?php echo $htmlId ?>-state">
    <fieldset id="<?php echo $htmlId ?>" class="config collapseable grid">
        <table class="data" cellspacing="0">
            <thead>
            <tr class="headings">
                <?php if ($this->_showInheritCheckbox()): ?>
                    <th style="width: 50px;"><?php echo $this->_getInheritLabel() ?></th>
                <?php endif; ?>
                <th style="width: 40%;">&nbsp;</th>
                <th style="width: 30%;"><?php echo $this->__('Send to Slack?') ?></th>
                <th style="width: 30%;"><?php echo $this->__('Highlight message?') ?></th>
            </tr>
            </thead>
            <tbody data-bind="foreach: notificationsData">
                <tr>
                    <?php if ($this->_showInheritCheckbox()): ?>
                        <td>
                        <span style="display: inline-block">
                            <input type="checkbox" value="1" data-bind="attr: {name: buildInheritName('inherit')}, checked: inherit, switch: inherit" />
                            <input type="hidden" data-bind="attr: {name: buildInheritName('send_type')}, value: inherit" />
                            <input type="hidden" data-bind="attr: {name: buildInheritName('custom_channel')}, value: inherit" />
                            <input type="hidden" data-bind="attr: {name: buildInheritName('colorize')}, value: inherit" />
                            <input type="hidden" data-bind="attr: {name: buildInheritName('color')}, value: inherit" />
                        </span>
                        </td>
                    <?php endif; ?>
                    <td data-bind="text: name"></td>
                    <td>
                        <select data-bind="chosen: {width: '200px'}, value: send_type,  disable: inherit, attr: {name: buildName('send_type')}" >
                            <option value="no"><?php echo $this->__('No') ?></option>
                            <option value="default"><?php echo $this->__('Yes - default channel') ?></option>
                            <option value="custom"><?php echo $this->__('Yes - custom channel') ?></option>
                        </select>
                        <span data-bind="visible: send_type() == 'custom'" style="display: inline-block">
                            <input type="text" class="" data-bind="value: custom_channel,  disable: inherit, attr: {name: buildName('custom_channel')}" />
                        </span>
                    </td>
                    <td>
                        <span style="display: inline-block">
                            <input type="hidden" value="0" data-bind="attr: {name: buildName('colorize')}" />
                            <input type="checkbox" value="1" data-bind="attr: {name: buildName('colorize')}, disable: inherit, checked: colorize, switch: colorize" />
                        </span>
                        <span data-bind="visible: colorize" style="display: inline-block">
                            <input type="text" class="" data-bind="value: color, attr: {name: buildName('color')}, disable: inherit, color: true" />
                        </span>
                    </td>
                </tr>
            </tbody>
        </table>
    </fieldset>
    <script type="text/javascript">
        Fieldset.applyCollapse('<?php echo $htmlId ?>');
        ko.applyBindings(new NotificationConfig.list(<?php echo $this->_getNotificationsJson() ?>), document.getElementById('<?php echo $htmlId ?>'));
    </script>
</div>