<?php 
/** 
* Moogento
* 
* SOFTWARE LICENSE
* 
* This source file is covered by the Moogento End User License Agreement
* that is bundled with this extension in the file License.html
* It is also available online here:
* http://www.moogento.com/License.html
* 
* NOTICE
* 
* If you customize this file please remember that it will be overwrtitten
* with any future upgrade installs. 
* If you'd like to add a feature which is not in this software, get in touch
* at www.moogento.com for a quote.
* 
* ID          pe+sMEDTrtCzNq3pehW9DJ0lnYtgqva4i4Z=
* File        after.phtml
* @category   Moogento
* @package    pickPack
* @copyright  Copyright (c) 2014 Moogento <info@moogento.com> / All rights reserved.
* @license    http://www.moogento.com/License.html
*/ 
 $measureUnit = $this->_getMeasureUnit(); ?>
<div id="moogento_weight_report">
<div class="moogento-weight">
    <?php if (Mage::helper('moogento_core')->isInstalled('Moogento_CourierRules')): ?>
        <?php foreach($this->_getCountryGroups() as $groupTitle => $groupValue): ?>
            &nbsp; &nbsp;<?php echo $groupTitle; ?>:<strong>&nbsp;
                <?php if ($groupValue['orders']): ?>
                    <?php echo $groupValue['weight'] . $measureUnit; ?> / <?php echo $groupValue['orders']?>
                <?php else:?>
                    0
                <?php endif;?>
            </strong>
        <?php endforeach;?>
    <?php else: ?>
        <?php $weightData = $this->_getWeightData() ?>
        <?php echo Mage::helper('moogento_shipeasy')->__('Weights/orders');?>:
        &nbsp;<strong><?php echo round($weightData['weight'], 2) . $measureUnit; ?> / <?php echo $weightData['orders']?></strong>
    <?php endif; ?>

</div>
</div>

