<?php 
/** 
* Moogento
* 
* SOFTWARE LICENSE
* 
* This source file is covered by the Moogento End User License Agreement
* that is bundled with this extension in the file License.html
* It is also available online here:
* http://www.moogento.com/License.html
* 
* NOTICE
* 
* If you customize this file please remember that it will be overwrtitten
* with any future upgrade installs. 
* If you'd like to add a feature which is not in this software, get in touch
* at www.moogento.com for a quote.
* 
* ID          pe+sMEDTrtCzNq3pehW9DJ0lnYtgqva4i4Z=
* File        scan.phtml
* @category   Moogento
* @package    pickPack
* @copyright  Copyright (c) 2014 Moogento <info@moogento.com> / All rights reserved.
* @license    http://www.moogento.com/License.html
*/ 
?>
<script type="text/javascript">

function clickButtonScan() {
    Modalbox.show(
        '<?php echo $this->getUrl('*/sales_order_scan/form')?>',
        {
            title: '<?php echo Mage::helper('moogento_shipeasy')->__('Barcode Processor') ?>',
            width: 1000,
            method: 'GET'
        }
    );
}

</script>
