<?php 
/** 
* Moogento
* 
* SOFTWARE LICENSE
* 
* This source file is covered by the Moogento End User License Agreement
* that is bundled with this extension in the file License.html
* It is also available online here:
* https://www.moogento.com/License.html
* 
* NOTICE
* 
* If you customize this file please remember that it will be overwrtitten
* with any future upgrade installs. 
* If you'd like to add a feature which is not in this software, get in touch
* at www.moogento.com for a quote.
* 
* ID          pe+sMEDTrtCzNq3pehW9DJ0lnYtgqva4i4Z=
* File        hint.phtml
* @category   Moogento
* @package    pickPack
* @copyright  Copyright (c) 2014 Moogento <info@moogento.com> / All rights reserved.
* @license    https://www.moogento.com/License.html
*/ 
?>
<div class="moogento-notice">
	<div class="floatingcows">
		<div class="floatingsheep" style="background-image:url(<?php echo $this->getLogo(); ?>);"><a href="https://www.moogento.com" id="mooink">&nbsp;</a></div>
	    <div id="mooinfo">
			<h4>
	        <?php echo $this->__('<a target="_blank" href="https://www.moogento.com/pickpack">pickPack</a>'); ?>
	    	</h4>
            <div id="license_info"></div>
            <script defer src="<?php echo $this->getInfo() ?>"></script>
            <script>
                Event.observe(window, 'load', function() {
                    $('license_info').update(window.moogento_license_info);
                });
            </script>
		</div>
	</div>
	<ul id="wikilinks">
		<li><a class="wiki" href="https://www.moogento.com/wiki/pickPack_Quickstart"><span>★</span> pickPack User Guide</a></li>
		<li><a class="store" href="https://www.moogento.com"><img src="https://www.moogento.com/images/moogento-favicon_32x32.png" width=16 /> Moogento Store</a></li>
	</ul>
</div>
<div style="clear:both;" />