<?php $_helper = Mage::helper('catsidebarnav'); ?>
<?php $showtype = $_helper->getShowType();?>
<?php $_menu = $this->renderCategoriesMenuHtml(0,'level-top') ?>
<?php if ($this->getUrl('') == $this->getUrl('*/*/*', array('_current' => true, '_use_rewrite' => true))): ?> 
<?php if($_helper->isEnabled()): ?>
	<?php if($showtype == 'static'):?>
		<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('css/magebuzz/catsidebarnav/static.css');?>" media="all" />
		<?php if($_menu): ?>
		<div class="block block-category-nav">
			<div class="block-title">
				<strong><span><?php echo $this->__('CATEGORIES') ?></span></strong>
			</div>
			<div class="block-content">
				<ul id="sidenav">
					<?php echo $_menu ?>
				</ul>
			</div>	
		</div>
		<?php endif ?>
	<?php elseif ($showtype == 'click-2-click'):?>
		<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('css/magebuzz/catsidebarnav/click.css');?>" media="all" />
<!--		<script src="http://jqueryjs.googlecode.com/files/jquery-1.3.2.min.js" type="text/javascript"></script>-->
		<script type="text/javascript">
			var $j = jQuery.noConflict(); 
			$j(document).ready(function () {
			  $j('#sidenav > li > a.show-cat').click(function(){
				$j('#sidenav li ul').slideUp();
				if (!$j(this).hasClass('active')){				  
				  $j(this).next().slideToggle();
				  $j('#sidenav li a.show-cat').removeClass('active');
				  $j(this).addClass('active');
				}
				else if ($j(this).hasClass('active')) {
					$j(this).removeClass('active');
				}
			  });
			  $j('#sidenav > li > ul > li > a.show-cat').click(function(){
				$j('#sidenav li ul li ul').slideUp();
				if (!$j(this).hasClass('active')){
				  $j(this).next().slideToggle();
				  $j('#sidenav li ul li a.show-cat').removeClass('active');
				  $j(this).addClass('active');
				}
				else if ($j(this).hasClass('active')) {
					$j(this).removeClass('active');
				}
			  });
			});
		</script>
		<?php if($_menu): ?>
		<div class="block block-category-nav">
			<div class="block-title">
				<strong><span><?php echo $this->__('CATEGORIES') ?></span></strong>
			</div>
			<div class="block-content">
				<ul id="sidenav">
					<?php echo $_menu ?>
				</ul>
			</div>	
		</div>
		<?php endif ?>
	<?php elseif ($showtype == 'fly-out'):?>
		<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('css/magebuzz/catsidebarnav/fly-out.css')?>" media="screen">
		<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/magebuzz/catsidebarnav/jquery-1.2.6.min.js')?>"></script>
		<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/magebuzz/catsidebarnav/hoverIntent.js')?>"></script>
		<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/magebuzz/catsidebarnav/superfish.js')?>"></script>
		<script type="text/javascript">
			jQuery.noConflict();
			jQuery(function(){
						//jQuery('ul.sf-menu').superfish();
					});
		</script>
		<?php if($_menu): ?>
		<div class="block block-category-nav">
			<div class="block-title">
				<strong><span><?php echo $this->__('CATEGORIES') ?></span></strong>
			</div>
			<div class="block-content">
				<ul class="sf-menu" id="left-nav">					
					<?php echo $_menu ?>
				</ul>
			</div>	
		</div>
		<?php endif ?>
	<?php endif ?>	
<?php endif ?>
 <div id="brands">
                            <div class="hadd_pink">BRANDS</div>
                            <div class="brand_link">
                                <ul>
                                    <li>
                                    	<a href="<?php echo $this->getUrl('manufacturers/anabolix') ?>">
                                   		<img class="grayimg" src="<?php echo $this->getSkinUrl('images/Brand/anabolix_gary.png'); ?>">
                                            <img class="" src="<?php echo $this->getSkinUrl('images/Brand/anabolix.png'); ?>">
                                        </a>
                                    </li>
                                   <li>
                                    	<a href="<?php echo $this->getUrl('manufacturers/arnold') ?>">
<!--                                    		<img class="grayimg" src="<?php //echo $this->getSkinUrl('images/Brand/ando_ser_gray.png'); ?>">-->
                                            <img class="grayscale" src="<?php echo $this->getSkinUrl('images/Brand/ando_ser_green.png'); ?>">
                                        </a>
                                    </li>
                                    <li>
                                    	<a href="<?php echo $this->getUrl('manufacturers/balance') ?>">
                                   		<img class="grayimg" src="<?php echo $this->getSkinUrl('images/Brand/BalanceSupplements_gry.png'); ?>">
                                            <img class="" src="<?php echo $this->getSkinUrl('images/Brand/BalanceSupplements_blk.png'); ?>">
                                        </a>
                                    </li>
                                    <li>
                                    	<a href="<?php echo $this->getUrl('manufacturers/bmp-labs') ?>">
<!--                                    		<img class="grayimg" src="<?php //echo $this->getSkinUrl('images/Brand/BPMLabs_Grey.png'); ?>">-->
                                            <img class="grayscale" src="<?php echo $this->getSkinUrl('images/Brand/BPMLabs_red.png'); ?>">
                                        </a>
                                    </li>
                                    <li>
                                    	<a href="<?php echo $this->getUrl('manufacturers/genetix') ?>">
                                    		<img class="grayimg" src="<?php echo $this->getSkinUrl('images/Brand/Genetix_Grey.png'); ?>">
                                            <img class="" src="<?php echo $this->getSkinUrl('images/Brand/Genetix.png'); ?>">
                                        </a>
                                    </li>
                                    <li>
                                    	<a href="<?php echo $this->getUrl('manufacturers/international-protein') ?>">
<!--                                    		<img class="grayimg" src="<?php //echo $this->getSkinUrl('images/Brand/InternationalProtein_Grey.png'); ?>">-->
                                            <img class="grayscale" src="<?php echo $this->getSkinUrl('images/Brand/InternationalProtein.png'); ?>">
                                        </a>
                                    </li>
                                    <li>
                                    	<a href="<?php echo $this->getUrl('manufacturers/beast') ?>">
                                    		<!-- <img class="grayimg" src="<?php //echo $this->getSkinUrl('images/Brand/NWH_Beast_gry.png'); ?>">-->
                                            <img class="grayscale" src="<?php echo $this->getSkinUrl('images/Brand/NWH_Beast_blue.png'); ?>">
                                        </a>
                                    </li>
                                    <li style="border:0px;">
                                       <a href="<?php echo $this->getUrl('manufacturers/scivation') ?>">
<!--                                    		<img class="grayimg" src="<?php //echo $this->getSkinUrl('images/Brand/Scivation_Grey.png'); ?>">-->
                                            <img class="grayscale" src="<?php echo $this->getSkinUrl('images/Brand/Scivation.png'); ?>">
                                        </a>
                                    </li>
                                </ul>
                            </div>
                            <a class="view_btn" href="<?php echo $this->getUrl('brands.html') ?>">VIEW ALL</a>
                      </div>	
<?php endif ?>
		