<?php
$_helper    = $this->helper('catalog/output');
$_category  = $this->getCurrentCategory();
$_category_name = $_helper->categoryAttribute($_category, $_category->getName(), 'name');

$url = $_category->getYoutubelink();
$_description=$_category->getDescription();

?>
<?php if (!$url && ! $_description): ?>
	<?php else: ?>
<div class="tabs">
	<ul class=" tab-links">
	<?php if ($_description): ?>
		<li class="active"><a href="#about" ><?php echo $this->__("ABOUT ") .  $_category_name?></a></li>
	<?php endif ?>
	<?php if ($url): ?>
			<?php if ($_description): ?>
				<li><a href="#video" ><?php echo $_category_name . $this->__(" VIDEO") ?></a></li>
				<?php else: ?>
				<li class="active"><a href="#video" ><?php echo $_category_name . $this->__(" VIDEO") ?></a></li>
			<?php endif ?>
	<?php endif ?>
	</ul>
	<div class="tab-content">
	<?php if ($_description): ?>
		<div id="about" class="tab active">
            <?php $checkVideo  = $_category->getThumbnail()?>
			<div class="about-box <?php echo $checkVideo ? "": "no-image"?>">
				<div class="about-text">
					<?php if($_description=$_category->getDescription()): ?>
						<div class=" std">
							<?php echo $_helper->categoryAttribute($_category, $_description, 'description') ?>
						</div>
						<a href="#" title="Read More" class="read-more-category show-less">Show More</a>
						<script type="text/javascript">
							jQuery('.about-text div').each(function () {
								jQuery('.about-text p:gt(0), .about-text ul, .about-text ol, .about-text br, .about-text img').hide();
								jQuery('a.read-more-category').click(function (e) {
								e.preventDefault();
								if (jQuery(this).hasClass('show-less'))
								{
									jQuery('.read-more-category').text('Show Less');
									jQuery(this).removeClass('show-less');
									jQuery(this).addClass('show-more');
								}
								else{
									jQuery('.read-more-category').text('Show More');
									jQuery(this).removeClass('show-more');
									jQuery(this).addClass('show-less');
								}
								jQuery('.about-text p:gt(0), .about-text ul, .about-text ol, .about-text br, .about-text img').slideToggle();
								});
							});
						</script>
					<?php endif; ?>
				</div>
			</div>
			
		</div>
	<?php endif ?>
		<?php if ($url): ?>
			<?php if ($_description): ?>
					<div id="video" class="tab" style="display:none">
						<iframe width="100%" src="<?php echo $url ?>" height="550"  frameborder="0" allowfullscreen ></iframe>
					</div>
				<?php else: ?>
					<div id="video" class="tab">
						<iframe width="100%" src="<?php echo $url ?>" height="550"  frameborder="0" allowfullscreen ></iframe>
					</div>
			<?php endif ?>
		<?php endif ?>
	</div>
</div>

<script type="text/javascript">
	jQuery(document).ready(function() {
		jQuery('.tabs .tab-links a').on('click', function(e)  {
			var currentAttrValue = jQuery(this).attr('href');
	        // Show/Hide Tabs
	        jQuery('.tabs ' + currentAttrValue).show().siblings().hide();
	        // Change/remove current tab to active
	        jQuery(this).parent('li').addClass('active').siblings().removeClass('active');
	        e.preventDefault();
	    });
        jQuery('.block-layered-nav').each(function(index){
            var parent=jQuery(this).parent()[0];
            if(!jQuery(parent).hasClass( "block-content")){
               // jQuery(this).hide();
            };
            });
	});
</script>
<?php endif ?>