<?php
/**
* Braintree Payments Extension
*
* This source file is subject to the Braintree Payment System Agreement (https://www.braintreepayments.com/legal)
*
* DISCLAIMER
* This file will not be supported if it is modified.
*
* @copyright   Copyright (c) 2015 Braintree. (https://www.braintreepayments.com/)
*/
?>
<?php $helper = Mage::helper('braintree_payments'); ?>
<?php if ($helper->isIwdOpcExtensionEnabled()) :?>
    <?php $_paypalCode = Braintree_Payments_Model_Paypal::PAYMENT_METHOD_CODE; ?>
    <script type="text/javascript">
        var nativeExtensionButton = $j_opc('.opc-btn-checkout');
        var paypalDivId = 'paypal-container';
        var braintreePaypalUtils = new BraintreeUtils();
        var formId = '<?php echo $this->getFormId()?>';
        var nonceInputId = '<?php echo $helper->getNonceInputId() ?>';
        braintreePaypalUtils.createHiddenInput({name: "payment[nonce]", id: nonceInputId}, formId);

        // Function to be called on success
        var onBraintreePayPalSuccess = function(){
            $(nonceInputId).disabled = false;
            nativeExtensionButton.click();
        };

        // Set up PayPal button
        var setupBraintreePayPal = function() {
            if ($(paypalDivId)) {
                $(paypalDivId).remove();
            }
            nativeExtensionButton.before('<div id="'+ paypalDivId + '"></div>');
            braintreePaypalUtils.setupPayPal(
                '<?php echo $helper->getToken() ?>',
                paypalDivId,
                '<?php echo $helper->getOrderAmount() ?>',
                '<?php echo $this->getCurrencyCode() ?>',
                '<?php echo $helper->getPayPalTitle() ?>',
                nonceInputId,
                false,
                false,
                '<?php echo $this->getLocale()?>',
                onBraintreePayPalSuccess,
                false,
                '<?php echo $helper->__('Please try again') ?>'
            );
        };

        // Remove Braintree PayPal button and show native extension button when braintree_paypal method is switched off
        document.observe("payment-method:switched-off", function(event) {
            if (event.memo.method_code == '<?php echo $_paypalCode?>') {
                if ($(paypalDivId)) {
                    $(paypalDivId).remove();
                }
                nativeExtensionButton.show();
            }
        });

        // Set up Braintree PayPal button and hide native extension button when braintree_paypal method is switched on
        document.observe("payment-method:switched", function(event) {
            if (event.memo.method_code == '<?php echo $_paypalCode?>') {
                nativeExtensionButton.hide();
                setupBraintreePayPal();
            } else {
                if ($(paypalDivId)) {
                    $(paypalDivId).remove();
                }
                nativeExtensionButton.show();
            }
        });
    </script>
<?php endif; ?>
