<?php
/**
* Braintree Payments Extension
*
* This source file is subject to the Braintree Payment System Agreement (https://www.braintreepayments.com/legal)
*
* DISCLAIMER
* This file will not be supported if it is modified.
*
* @copyright   Copyright (c) 2015 Braintree. (https://www.braintreepayments.com/)
*/
?>
<ul class="form-list braintree-paypal" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
    <li>
        <p><strong><?php echo $this->__('You will be asked for PayPal login on next step');?></strong></p>
    </li>
</ul>
