<?php
/**
* Braintree Payments Extension
*
* This source file is subject to the Braintree Payment System Agreement (https://www.braintreepayments.com/legal)
*
* DISCLAIMER
* This file will not be supported if it is modified.
*
* @copyright   Copyright (c) 2015 Braintree. (https://www.braintreepayments.com/)
*/
?>
<script type="text/javascript">
var button = $$('button[type=submit][class~="btn-checkout"]')[0];
var divId = 'paypal-container';
    <?php if ($this->isBraintreePayPalMethod()): ?>
        if (typeof braintreePaypalUtils !== 'object') {
            var braintreePaypalUtils = new BraintreeUtils();
        }
        var formId = '<?php echo $this->getFormId()?>';
        if (!$(formId)) {
            formId = 'co-payment-form';
        }
        var nonceInputId = '<?php echo Mage::helper('braintree_payments')->getNonceInputId() ?>';
        braintreePaypalUtils.createHiddenInput(
            {name: "payment[nonce]", id: nonceInputId},
            formId
        );
        var onSuccess = function() {
            $(nonceInputId).disabled = false;
            review.save();
        };
        if (!$(divId)) {
            var div = '<div id="'+ divId + '" style="float:left"></div>';
            button.insert({before: div});
            braintreePaypalUtils.setupPayPal(
                '<?php echo Mage::helper('braintree_payments')->getToken() ?>',
                divId,
                '<?php echo Mage::helper('braintree_payments')->getOrderAmount() ?>',
                '<?php echo $this->getCurrencyCode() ?>',
                '<?php echo Mage::helper('braintree_payments')->getPayPalTitle() ?>',
                nonceInputId,
                false,
                false,
                '<?php echo $this->getLocale()?>',
                onSuccess,
                false,
                '<?php echo Mage::helper('braintree_payments')->__('Please try again') ?>'
            );
        }
        button.hide();
    <?php else: ?>
        button.show();
    <?php endif; ?>
</script>
