<?php
/**
* Braintree Payments Extension
*
* This source file is subject to the Braintree Payment System Agreement (https://www.braintreepayments.com/legal)
*
* DISCLAIMER
* This file will not be supported if it is modified.
*
* @copyright   Copyright (c) 2015 Braintree. (https://www.braintreepayments.com/)
*/
?>
<?php echo $this->getMessagesBlock()->toHtml() ?>
<div class="info-set col1-set">
    <h2 class="legend"><?php echo $this->__('Shipping Information') ?></h2>
    <div class="col-1">
        <div class="box">
            <div class="box-title">
                <h3><?php echo $this->getAction() . ' ' . $this->__('Shipping Address') ?></h3>
            </div>
            <div class="box-content">
                <form action="<?php echo $this->getSaveUrl() ?>" method="post" id="shipping-form">
                    <ul class="form-list">
                    <?php if ($this->customerHasAddresses()): ?>
                       <li class="wide">
                           <label for="shipping-address-select"><?php echo $this->__('Select a shipping address from your address book or enter a new address.') ?></label>
                           <div class="input-box">
                               <?php echo $this->getAddressesHtmlSelect() ?>
                           </div>
                       </li>
                    <?php endif ?>
                        <li id="shipping-new-address-form"<?php if ($this->customerHasAddresses()): ?> style="display:none;"<?php endif ?>>
                            <fieldset>
                                <input type="hidden" name="shipping[address_id]" value="<?php echo $this->getAddress()->getId() ?>" id="shipping:address_id" />
                                <ul>
                                    <li class="fields"><?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getAddress())->setFieldIdFormat('shipping:%s')->setFieldNameFormat('shipping[%s]')->toHtml() ?></li>
                                    <li class="fields">
                                        <div class="fields">
                                            <label for="shipping:company"><?php echo $this->__('Company') ?></label>
                                            <div class="input-box">
                                                <input type="text" id="shipping:company" name="shipping[company]" value="<?php echo $this->escapeHtml($this->getAddress()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>" />
                                            </div>
                                        </div>
                                    </li>
                            <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
                                    <li class="wide">
                                        <label for="shipping:street1" class="required"><em>*</em><?php echo $this->__('Address') ?></label>
                                        <div class="input-box">
                                            <input type="text" title="<?php echo $this->__('Street Address') ?>" name="shipping[street][]" id="shipping:street1" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?>" class="input-text <?php echo $_streetValidationClass ?>" />
                                        </div>
                                    </li>
                            <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                            <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                                    <li class="wide">
                                        <div class="input-box">
                                            <input type="text" title="<?php echo $this->__('Street Address %s', $_i) ?>" name="shipping[street][]" id="shipping:street<?php echo $_i ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet($_i)) ?>" class="input-text <?php echo $_streetValidationClass ?>" />
                                        </div>
                                    </li>
                            <?php endfor; ?>
                                    <?php if ($this->helper('customer/address')->isVatAttributeVisible()) : ?>
                                    <li class="wide">
                                        <label for="billing:vat_id"><?php echo $this->__('VAT Number'); ?></label>
                                        <div class="input-box">
                                            <input type="text" id="shipping:vat_id" name="shipping[vat_id]" value="<?php echo $this->escapeHtml($this->getAddress()->getVatId()); ?>" title="<?php echo $this->__('VAT Number'); ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('vat_id') ?>" />
                                        </div>
                                    </li>
                                    <?php endif; ?>
                                    <li class="fields">
                                        <div class="field">
                                            <label for="shipping:city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
                                            <div class="input-box">
                                                <input type="text" title="<?php echo $this->__('City') ?>" name="shipping[city]" value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="shipping:city" />
                                            </div>
                                        </div>
                                        <div class="field">
                                            <label for="shipping:region" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
                                            <div class="input-box">
                                                <select id="shipping:region_id" name="shipping[region_id]" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;">
                                                    <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                                                </select>
                                                <script type="text/javascript">
                                                //<![CDATA[
                                                    $('shipping:region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
                                                //]]>
                                                </script>
                                                <input type="text" id="shipping:region" name="shipping[region]" value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>" title="<?php echo $this->__('State/Province') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" style="display:none;" />
                                            </div>
                                        </div>
                                    </li>
                                    <li class="fields">
                                        <div class="field">
                                            <label for="shipping:postcode" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
                                            <div class="input-box">
                                                <input type="text" title="<?php echo $this->__('Zip/Postal Code') ?>" name="shipping[postcode]" id="shipping:postcode" value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>" class="input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" />
                                            </div>
                                        </div>
                                        <div class="field">
                                            <label for="shipping:country_id" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
                                            <div class="input-box">
                                                <?php echo $this->getCountryHtmlSelect() ?>
                                            </div>
                                        </div>
                                    </li>
                                    <li class="fields">
                                        <div class="field">
                                            <label for="shipping:telephone" class="required"><em>*</em><?php echo $this->__('Telephone') ?></label>
                                            <div class="input-box">
                                                <input type="text" name="shipping[telephone]" value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" id="shipping:telephone" />
                                            </div>
                                        </div>
                                        <div class="field">
                                            <label for="shipping:fax"><?php echo $this->__('Fax') ?></label>
                                            <div class="input-box">
                                                <input type="text" name="shipping[fax]" value="<?php echo $this->escapeHtml($this->getAddress()->getFax()) ?>" title="<?php echo $this->__('Fax') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('fax') ?>" id="shipping:fax" />
                                            </div>
                                        </div>
                                    </li>
                                </ul>
                            </fieldset>
                        </li>
                    </ul>
                    <div class="buttons-set" id="shipping-buttons-container">
                        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
                        <button type="button" class="button" title="<?php echo $this->__('Save') ?>" onclick="shippingForm.submitForm(this)"><span><span><?php echo $this->__('Save') ?></span></span></button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
//<![CDATA[
    var shippingForm = new VarienForm('shipping-form');
    shippingForm.submitForm = function(button) {
        if (this.validator.validate()) {
            $('shipping-form').submit();
        }
    }.bind(shippingForm);
    var shippingRegionUpdater = new RegionUpdater('shipping:country_id', 'shipping:region', 'shipping:region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'shipping:postcode');
    $('shipping-address-select').observe('change', function(){
        if (!$('shipping-address-select').value) {
            $('shipping-new-address-form').show();
        } else {
            $('shipping-new-address-form').hide();
        }
    });
//]]>
</script>
