<?php
/**
* Braintree Payments Extension
*
* This source file is subject to the Braintree Payment System Agreement (https://www.braintreepayments.com/legal)
*
* DISCLAIMER
* This file will not be supported if it is modified.
*
* @copyright   Copyright (c) 2015 Braintree. (https://www.braintreepayments.com/)
*/
?>
<div class="page-title">
    <h1><?php echo $this->__('Review Order') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->toHtml() ?>
<?php if ($this->getShippingAddress()): ?>
    <div class="info-set col2-set">
        <h2 class="legend"><?php echo $this->__('Shipping Information') ?></h2>
        <div class="col-1">
            <div class="box">
                <div class="box-title">
                    <h3><?php echo $this->__('Shipping Address') ?><span class="separator">  | </span> <a href="<?php echo $this->getEditUrl() ?>"><?php echo $this->__('Edit') ?></a></h3>
                </div>
                <div class="box-content">
                    <address><?php echo $this->renderAddress($this->getShippingAddress())?></address>
                </div>
            </div>
        </div>
        <div class="col-2">
            <div class="box">
                <div class="box-title">
                    <h3><?php echo $this->__('Shipping Method') ?></h3>
                </div>
                <div class="box-content">
                    <form method="post" id="shipping_method_form" action="<?php echo $this->getShippingMethodSubmitUrl() ?>">
                        <?php if ($groups = $this->getShippingRateGroups()):?>
                            <?php $currentRate = $this->getCurrentShippingRate(); ?>
                            <fieldset>
                                <select name="shipping_method" id="shipping_method" style="width:250px;" class="required-entry">
                                    <?php if (!$currentRate):?>
                                        <option value=""><?php echo $this->__('Please select a shipping method...') ?></option>
                                    <?php endif;?>
                                    <?php foreach ($groups as $code => $rates):?>
                                        <optgroup label="<?php echo $this->escapeHtml($this->getCarrierName($code)) ?>" style="font-style:normal;">
                                            <?php foreach ($rates as $rate):?>
                                                <option value="<?php echo $this->renderShippingRateValue($rate)?>"<?php echo ($currentRate === $rate) ? ' selected="selected"' : '' ;?>>
                                                    <?php echo $this->renderShippingRateOption($rate)?>
                                                </option>
                                            <?php endforeach;?>
                                        </optgroup>
                                    <?php endforeach;?>
                                </select>
                            </fieldset>
                        <?php else: ?>
                            <p><strong><?php echo $this->__('Sorry, no quotes are available for this order at this time.') ?></strong></p>
                        <?php endif;?>
                    </form>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>

<div class="info-set col2-set">
    <h2 class="legend"><?php echo $this->__('Billing Information') ?></h2>
    <div class="col-1">
        <div class="box">
            <div class="box-title">
                <h3><?php echo $this->__('Billing Address') ?></h3>
            </div>
            <div class="box-content">
                <address><?php echo $this->renderAddress($this->getBillingAddress())?></address>
            </div>
        </div>
    </div>
    <div class="col-2">
        <div class="box">
            <div class="box-title">
                <h3><?php echo $this->__('Payment Method') ?></h3>
            </div>
            <div class="box-content">
                <?php echo $this->escapeHtml($this->getPaymentMethodTitle()) ?>
            </div>
        </div>
    </div>
</div>

<div class="info-set">
    <h2 class="legend"><?php echo $this->__('Items in Your Shopping Cart') ?><span class="separator"> | </span><a href="<?php echo $this->getUrl('checkout/cart') ?>"><?php echo $this->__('Edit Shopping Cart') ?></a></h2>
    <div id="details-reload">
        <?php echo $this->getChildHtml('details') ?>
    </div>
</div>
<form method="post" id="order_review_form" action="<?php echo $this->getPlaceOrderUrl() ?>">
    <?php echo $this->getChildHtml('agreements'); ?>
    <div class="buttons-set buttons-set-order" id="review-buttons-container">
        <button type="button" id="review_button" value="<?php echo $this->__('Place Order') ?>" class="button btn-checkout"><span><span><?php echo $this->__('Place Order') ?></span></span></button>
        <span class="please-wait" id="review-please-wait" style="display:none;">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Submitting order information...') ?>" title="<?php echo $this->__('Submitting order information...') ?>" class="v-middle" /> <?php echo $this->__('Submitting order information...') ?>
        </span>
    </div>
</form>
<script type="text/javascript">
    //<![CDATA[
    BraintreePayPal = new OrderReviewController($('order_review_form'), $('review_button'),
        $('shipping_method'), $('shipping_method_form'), 'details-reload'
    );
    BraintreePayPal.addPleaseWait($('review-please-wait'));
    //]]>
</script>
