
<?php if ($this->displayBoth()): ?>
    <tr class="os_part mrgn_t5">
        <td style="<?php echo $this->getStyle() ?>" class="a-right left font14_gry" colspan="<?php echo $this->getColspan(); ?>">
            <?php echo $this->helper('tax')->__('Subtotal (Excl. Tax)') ?>
        </td>
        <td style="<?php echo $this->getStyle() ?>" class="a-right right font18_blk">
            <?php echo $this->helper('checkout')->formatPrice($this->getTotal()->getValueExclTax()) ?>
        </td>
    </tr>
    <tr class="os_part mrgn_t5">
        <td style="<?php echo $this->getStyle() ?>" class="a-right left font14_gry" colspan="<?php echo $this->getColspan(); ?>">
            <?php echo $this->helper('tax')->__('Subtotal (Incl. Tax)') ?>
        </td>
        <td style="<?php echo $this->getStyle() ?>" class="a-right right font18_blk">
            <?php echo $this->helper('checkout')->formatPrice($this->getTotal()->getValueInclTax()) ?>
        </td>
    </tr>
    <?php else : ?>
    <tr class="os_part mrgn_t5">
        <td style="<?php echo $this->getStyle() ?>" class="a-right left font14_gry" colspan="<?php echo $this->getColspan(); ?>">
            <?php echo $this->getTotal()->getTitle() ?>
        </td>
        <td style="<?php echo $this->getStyle() ?>" class="a-right right font18_blk">
            <?php echo $this->helper('checkout')->formatPrice($this->getTotal()->getValue()) ?>
        </td>
    </tr>
<?php endif ?>
