<?php 
/** 
* Moogento
* 
* SOFTWARE LICENSE
* 
* This source file is covered by the Moogento End User License Agreement
* that is bundled with this extension in the file License.html
* It is also available online here:
* http://www.moogento.com/License.html
* 
* NOTICE
* 
* If you customize this file please remember that it will be overwrtitten
* with any future upgrade installs. 
* If you'd like to add a feature which is not in this software, get in touch
* at www.moogento.com for a quote.
* 
* ID          pe+sMEDTrtCzNq3pehW9DJ0lnYtgqva4i4Z=
* File        extraaction.phtml
* @category   Moogento
* @package    pickPack
* @copyright  Copyright (c) 2014 Moogento <info@moogento.com> / All rights reserved.
* @license    http://www.moogento.com/License.html
*/ 
?>
<div class="entry-edit">
    <fieldset>
        <span class="field-row">
            <label class="normal" for="<?php echo $this->getHtmlId() ?>-select"><?php echo Mage::helper('moogento_shipeasy')->__('Additional Action') ?></label>
            <select id="<?php echo $this->getHtmlId() ?>-select" class="select absolute-advice local-validation" name="scan[<?php echo $this->getHtmlId() ?>][action]">
                <option value=""></option>
                <?php foreach ($this->getItems() as $_item): ?>
                    <option value="<?php echo $_item->getId() ?>"><?php echo $_item->getLabel() ?></option>
                <?php endforeach; ?>
            </select>
        </span>
        <span class="outer-span" id="<?php echo $this->getHtmlId() ?>-form-hiddens"></span>
        <span class="outer-span" id="<?php echo $this->getHtmlId() ?>-form-additional"></span>
    </fieldset>
</div>

<div class="no-display">
    <?php foreach ($this->getItems() as $_item): ?>
        <div id="<?php echo $this->getHtmlId() ?>-item-<?php echo $_item->getId() ?>-block">
            <?php echo $_item->getAdditionalActionBlockHtml() ?>
        </div>
    <?php endforeach; ?>
</div>