<?php
/**
 * @category    Fishpig
 * @package     Fishpig_AttributeSplash
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>


<?php if ($splashPage = $this->getSplashPage()): ?>
    <?php
    $pageName = $splashPage->getData('url_key');
    $beforeDescription = Mage::app()->getLayout()->createBlock('zblocks/block')->setPosition($pageName . '_before_description')->toHtml();
    $afterContent = Mage::app()->getLayout()->createBlock('zblocks/block')->setPosition($pageName . '_after_content')->toHtml();
    $afterDescription = Mage::app()->getLayout()->createBlock('zblocks/block')->setPosition($pageName . '_after_description')->toHtml();
    if (strlen($beforeDescription) === 0) {
        $beforeDescription = Mage::app()->getLayout()->createBlock('zblocks/block')->setPosition('brands_before_description')->toHtml();
    }
    if (strlen($afterContent) === 0) {
        $afterContent = Mage::app()->getLayout()->createBlock('zblocks/block')->setPosition('brands_after_content')->toHtml();
    }
    
    if(strlen($afterDescription) === 0 ) {
    $afterDescription = Mage::app()->getLayout()->createBlock('zblocks/block')->setPosition('brands_after_description')->toHtml();    
    }
    ?>
    <?php if ($splashPage->getImage()): ?>
        <div class="banner-image">
            <p class="splash-image">
                <?php if ($splashPage->getImageUrl()): ?>
                    <a href="<?php echo $splashPage->getImageUrl() ?>" title="<?php echo $this->escapeHtml($splashPage->getName()) ?>">
                    <?php endif; ?>
                    <img src="<?php echo $this->helper('attributeSplash/image')->init($splashPage, 'image')->resize(null, null) ?>" alt="<?php echo $this->escapeHtml($splashPage->getName()) ?>" style="width:100%; height:auto"/>
                    <?php if ($splashPage->getImageUrl()): ?>
                    </a>
                <?php endif; ?>
            </p>
        </div>
    <?php endif; ?>
    <?php if (!$splashPage->getVideo() && !$splashPage->getShortDescription()): ?>
    <?php else: ?>


        <div class="tabs">
            <ul class=" tab-links">
                <?php if ($shortDescription = $splashPage->getShortDescription()): ?>
                    <li class="active"><a href="#about" ><?php echo $this->__("ABOUT ") . $this->escapeHtml($splashPage->getName()) ?></a></li>
                <?php endif ?>
                <?php if ($splashPage->getVideo()): ?>
                    <?php if ($shortDescription = $splashPage->getShortDescription()): ?>
                        <li><a href="#video" ><?php echo $this->escapeHtml($splashPage->getName()) . $this->__(" VIDEO") ?></a></li>
                    <?php else : ?>
                        <li class="active"><a href="#video" ><?php echo $this->escapeHtml($splashPage->getName()) . $this->__(" VIDEO") ?></a></li>
                    <?php endif ?>
                <?php endif ?>
            </ul>
            <div class="tab-content">
                <?php echo $beforeDescription ?>
                <?php if ($shortDescription = $splashPage->getShortDescription()): ?>
                    <div id="about" class="tab active">
                        <div class="about-box">
                            <div class="about-text grid12-8">
                                <div class="splash-description std"><?php echo $shortDescription ?></div>
                            </div>
                            <div class="about-img grid12-4">
                                <?php if ($splashPage->getThumbnailHover()): ?>
                                    <p class="splash-image">
                                        <img src="<?php echo $splashPage->getThumbnailHover() ?>" alt="<?php echo $this->escapeHtml($splashPage->getName()) ?>"/>
                                    </p>
                                <?php endif; ?>
                            </div>
                        </div>

                    </div>
                <?php endif; ?>

                <?php if ($splashPage->getVideo()): ?>
                    <?php if ($shortDescription = $splashPage->getShortDescription()): ?>
                        <div id="video" class="tab" style="display:none">
                            <?php echo $splashPage->getVideo() ?>
                        </div>
                    <?php else : ?>
                        <div id="video" class="tab">
                            <?php echo $splashPage->getVideo() ?>
                        </div>
                    <?php endif ?>

                <?php endif ?>
                <?php echo $afterDescription; ?>
            </div>
        </div>
        <?php echo $afterContent; ?>
    <?php endif ?>	
    <script type="text/javascript">
        jQuery(document).ready(function () {
            jQuery('.tabs .tab-links a').on('click', function (e) {
                var currentAttrValue = jQuery(this).attr('href');
                // Show/Hide Tabs
                jQuery('.tabs ' + currentAttrValue).show().siblings().hide();
                // Change/remove current tab to active
                jQuery(this).parent('li').addClass('active').siblings().removeClass('active');
                e.preventDefault();
            });
        });
    </script>

    <?php if ($this->isContentMode()): ?>
        <?php echo $this->getCmsBlockHtml() ?>
    <?php elseif ($this->isMixedMode()): ?>
        <?php echo $this->getCmsBlockHtml() ?>
        <?php echo $this->getProductListHtml() ?>
    <?php else: ?>
        <?php echo $this->getProductListHtml() ?>
    <?php endif; ?>
    <?php if ($description = $splashPage->getDescription()): ?>
        <div class="splash-description-full std"><?php echo $description ?></div>
    <?php endif; ?>
<?php endif; ?>