<?php
    $_pageHelper = Mage::helper('local/page');
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
    <?php echo $this->getChildHtml('head') ?>
</head>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
    <?php echo $this->getChildHtml('after_body_start') ?>
    <main class="<?php echo $_pageHelper->additionalMainPageClass(); ?>"> 
        <div class="accountbg">
            <div class="wrap">
                <div class="comman">
                    <?php echo $this->getChildHtml('header') ?>
                </div>
                <?php echo $this->getChildHtml('pre_content') ?>
            </div>
        </div>
        <?php echo $this->getChildHtml('global_notices') ?>
        <div class="inner_middle">
            <div class="containar">
                <div class="comman">
                    <div id="middle" class="col-main">
                        <?php echo $this->getChildHtml('global_messages') ?>
                        <?php echo $this->getChildHtml('content') ?>
                    </div>
                </div>
            </div>
        </div>
        <?php echo $this->getChildHtml('pre_footer') ?>
        <?php echo $this->getChildHtml('footer') ?>
        <?php echo $this->getChildHtml('global_cookie_notice') ?>
        <?php echo $this->getChildHtml('before_body_end') ?>
    </main>
    <?php echo $this->getAbsoluteFooter() ?>
</body>
</html>
