<?php
    $_pageHelper = Mage::helper('local/page');
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
    <?php echo $this->getChildHtml('head') ?>
</head>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
    <?php echo $this->getChildHtml('after_body_start') ?>
    <main class="<?php echo $_pageHelper->additionalMainPageClass(); ?>"> 
        <?php if ($_pageHelper->onlyContent()): ?>
            <?php echo $this->getChildHtml('header') ?>
        <?php endif ?>
        <?php echo $this->getChildHtml('global_notices') ?>
        <div class="<?php echo ($_pageHelper->isHome()) ? 'homebg' : 'innerbg' ?>">
            <div class="containar">
                <div class="comman">
                    <?php if (!$_pageHelper->onlyContent()): ?>
                        <?php echo $this->getChildHtml('header') ?>
                        <?php echo $this->getChildHtml('breadcrumbs') ?>
                    <?php endif ?>
                    <?php echo $this->getChildHtml('pre_content') ?>
                    <div id="middle" class="col-main">
                        <?php echo $this->getChildHtml('global_messages') ?>
                        <?php echo $this->getChildHtml('content') ?>
                    </div>
                </div>
            </div>
        </div>
        <?php echo $this->getChildHtml('pre_footer') ?>
        <?php echo $this->getChildHtml('footer') ?>
        <?php echo $this->getChildHtml('global_cookie_notice') ?>
        <?php echo $this->getChildHtml('before_body_end') ?>
    </main>
    <?php echo $this->getAbsoluteFooter() ?>
</body>
</html>
