<?php
    $accountpage = Mage::app()->getFrontController()->getRequest()->getRequestedActionName();
    if ($accountpage == 'bestsellers') {
        $viewAllLable = $this->__('TOP SELLERS');
    }

    if ($accountpage == 'featured'){
        $viewAllLable = $this->__('WHAT\'S NEW');
    }
?>
<?php if (Mage::app()->getFrontController()->getRequest()->getRouteName() == 'catalogextensions'): ?>
    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('feature_single_product')->toHtml() ?>
    <div class="hadd_pink2 page-title category-title" style="float:none">
        <h1><?php echo $viewAllLable ?></h1>
        <div class="triangle-bottomleft"></div>
    </div>
<?php endif ?>

<?php
    $_helper = $this->helper('catalog/output');
    /*$this->setData('column_count',4);
    if (isset($_REQUEST['g']) && $_REQUEST['g'] != '') {
        $_productCollection = Mage::getModel('catalog/product')->getCollection()
            ->addAttributeToSelect('*')
            ->addFieldToFilter(
                array(
                    array('attribute'=>'Goal','finset'=>$_REQUEST['g']),
                )
            );
    } else {*/
        $_productCollection = $this->getLoadedProductCollection();
    //}
?>

<?php if (!$_productCollection->count()): ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
    <?php echo $this->getToolbarHtml() ?>

    <?php // List mode  ?>
    <?php if ($this->getMode() != 'grid'): ?>
        <div class="category-products prod_slider">
            <?php $_iterator = 0;$j=0 ?>
            <ol class="products-list" id="products-list">
                <?php foreach ($_productCollection as $_product): ?>
                    <?php $j++ ?>
                    <li class="item<?php if (++$_iterator == sizeof($_productCollection)): ?> last<?php endif ?>">
                    <?php // Product Image ?>
                        <div class="left">
                            <a data-link="<?php echo $j ?>" id="pb_item_<?php echo $_product->getId() ?>" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="EnableQuickView product-image">
                                <div class="productimage">
                                    <span><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135) ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></span>
                                </div>
                            </a>

                            <?php // Product description ?>
                            <div class="fwimg_detl">

                                <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true) ?>
                                <h5>
                                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>">
                                        <?php
                                            $prodname =  $_helper->productAttribute($_product, $_product->getName(), 'name'); 
                                            if (strlen($prodname) > 18) {
                                                echo substr($prodname, 0, 18) . '...';
                                            } else {
                                                echo $prodname;
                                            }
                                        ?>
                                    </a>
                                </h5>
                                <?php if ($_product->getRatingSummary()): ?>
                                    <?php echo $this->getReviewsSummaryHtml($_product) ?>
                                <?php endif ?>


                                <div class="comman font14_blk">
                                    <?php
                                        $shorDescription = strip_tags($_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description'));
                                        if (strlen($shorDescription) > 30) {
                                            echo substr($shorDescription, 0, 30) . '...';
                                        } else {
                                            echo $shorDescription;
                                        }
                                    ?>
                                </div>
                                <div class="comman mrgn_t10 font12_gry">
                                    <?php
                                        $Description = strip_tags($_helper->productAttribute($_product, $_product->getDescription(), 'description'));
                                        if (strlen($Description) > 280) {
                                            echo substr($Description, 0, 280) . '...';
                                        } else {
                                            echo $Description;
                                        }
                                    ?>
                                </div>

                                <!--
                                <a href="<?php //echo $_product->getProductUrl() ?>" title="<?php //echo $_productNameStripped ?>" class="link-learn link12_red"><?php //echo $this->__('Learn More') ?></a>
                                <ul class="add-to-links">
                                    <?php //if ($this->helper('wishlist')->isAllow()) :  ?>
                                         <li><a href="<?php //echo $this->helper('wishlist')->getAddUrl($_product)  ?>" class="link-wishlist"><?php //echo $this->__('Add to Wishlist') ?></a></li>
                                    <?php //endif;  ?>
                                </ul>
                                -->
                            </div>
                        </div>
                        <div class="right">
                            <div class="pricing">
                                <ul>
                                    <?php echo $this->getPriceHtml($_product, true) ?>
                                    <?php if ($_compareUrl = $this->getAddToCompareUrl($_product)): ?>
                                        <li class="mrgn_t30"><a class="link12_red addtocampare" href="<?php echo $_compareUrl ?>">+ <?php echo $this->__('Add to compare') ?></a></li>
                                    <?php endif ?>
                                    <?php if ($_product->isSaleable()): ?>
                                        <!--
                                        <p>
                                            <button type="button" title="<?php //echo $this->__('Add to Cart')  ?>" class="button btn-cart" onclick="setLocation('<?php //echo $this->getAddToCartUrl($_product)  ?>')">
                                            <span>
                                            <span><?php //echo $this->__('Add to Cart')  ?></span></span></button>
                                        </p>

                                        <li>
                                            <a onclick="setLocation('<?php //echo $this->getAddToCartUrl($_product) ?>')" class="buy_btn">BUY NOW</a>
                                        </li>
                                        -->

                                        <li>
                                            <a onclick="setLocation('<?php echo $_product->getProductUrl() ?>')" class="buy_btn"><?php echo $this->__('VIEW DETAILS') ?></a>
                                        </li>                                        
                                    <?php else: ?>
                                        <li class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></li>
                                    <?php endif ?>
                                </ul>
                            </div> 
                        </div>
                    </li>
                    <div id="<?php echo $j ?>" class="slidmain product_data listmode" style="float:left; display:none;"></div>
                <?php endforeach ?>
            </ol>
        </div>
        <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

    <?php else: ?>

        <div class="category-products prod_slider">
            <?php // Grid Mode ?>

            <?php
                $_collectionSize = $_productCollection->count();
                $_columnCount = $this->getColumnCount();
                $i=0;
                $j=0;
            ?>
            <?php foreach ($_productCollection as $_product): ?>
                <?php if ($i++%$_columnCount==0): $j++;  ?>
                    <ul class="products-grid">
                <?php endif ?>
                    <li class="item<?php if (($i-1)%$_columnCount==0): ?> first<?php elseif ($i%$_columnCount==0): ?> last<?php endif ?>">
                        <a data-link="<?php echo $j ?>" id="pb_item_<?php echo $_product->getId() ?>" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="EnableQuickView product-image">
                            <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135) ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                        </a>
                        <div class="quickview">&nbsp;</div>
                        <h2 class="product-name">
                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
                                <?php
                                    $prodname =  $_helper->productAttribute($_product, $_product->getName(), 'name'); 
                                    if (strlen($prodname) > 18) {
                                        echo substr($prodname, 0, 18) . '...';
                                    } else {
                                        echo $prodname;
                                    }
                                ?>
                            </a>
                        </h2>
                        <div class="font12_gry">
                            <?php 
                                $length = $this->htmlEscape(strip_tags($_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description')));
                                if (strlen($length) > 25) {
                                    echo substr($length, 0, 25) . '...'; 
                                } else { 
                                    echo substr($length, 0, 25);
                                }
                            ?>
                        </div>
                        <?php if($_product->getRatingSummary()): ?>
                            <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                        <?php endif ?>
                        <?php echo $this->getPriceHtml($_product, true) ?>
                        <div class="actions">
                            <ul class="add-to-links">
                                <?php if ($this->helper('wishlist')->isAllow()): ?>
                                    <!--<li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>-->
                                <?php endif ?>
                                <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                    <li style="margin-bottom:5px;" class="mrgn_t5"><a class="link12_red" href="<?php echo $_compareUrl ?>"><?php echo $this->__('+ Add to compare') ?></a></li>    
                                <?php endif ?>
                            </ul>
                            <?php if($_product->isSaleable()): ?>
                                <!--<button type="button" title="<?php //echo $this->__('BUY NOW') ?>" class="button btn-cart" onclick="setLocation('<?php //echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php //echo $this->__('BUY NOW') ?></span></span></button>-->
                                <!--<button type="button" title="<?php echo $this->__('BUY NOW') ?>" class="button btn-cart" onclick="setLocation('<?php echo $_product->getProductUrl() ?>')"><span><span><?php echo $this->__('BUY NOW') ?></span></span></button>-->
                            <?php else: ?>
                                <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                            <?php endif ?>
                        </div>
                    </li>
                <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
                    </ul>
                    <div id="<?php echo $j ?>" class="slidmain product_data" style="float: left;display:none;"></div>
                <?php endif ?>
            <?php endforeach ?>
            <script>
                decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])
            </script>
        <?php endif ?>

        <div class="toolbar-bottom">
            <?php echo  $this->getToolbarBlock()->setTemplate('catalog/product/list/toolbar-botton.phtml')->toHtml() ?>
        </div>
    </div>
<?php endif ?>
